employees = [
    """User ID: 1, Name: Alice Smith""",
    """User ID: 2, Name: Bob Johnson""",
    """User ID: 3, Name: Frank Miller""",
    """User ID: 4, Name: David Brown""",
    """User ID: 5, Name: Mia White""",
    """User ID: 6, Name: Henry Lee""",
    """User ID: 7, Name: Karen Anderson""",
    """User ID: 8, Name: Eve Wilson""",
    """User ID: 9, Name: Isabel Scott""",
    """User ID: 10, Name: Noah Harris""",
    """User ID: 11, Name: Quinn Allen""",
    """User ID: 12, Name: Leo Thomas""",
    """User ID: 13, Name: Jack Martinez""",
    """User ID: 14, Name: Carol Taylor""",
    """User ID: 15, Name: Olivia Walker""",
    """User ID: 16, Name: Grace Davis""",
    """User ID: 17, Name: Peter Hall""",
    """User ID: 18, Name: Sam King""",
    """User ID: 19, Name: Rachel Young""",
    """User ID: 20, Name: Tina Wright"""
]
