# Generated by Django 4.2.16 on 2024-11-02 20:03

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector_data", pgvector.django.vector.VectorField(dimensions=512)),
                ("text_data", models.TextField()),
            ],
        ),
    ]
