# Generated by Django 4.2.16 on 2024-11-03 03:07

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('text', models.TextField()),
                ('author', pgvector.django.vector.VectorField(dimensions=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
