# Generated by Django 4.2.16 on 2024-11-03 08:40

from django.conf import settings
from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='base_id',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sources',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
