# Generated by Django 4.2.16 on 2024-11-03 07:01

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='summ_emb',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
